---
name: Create a new Component Definition

on:
  workflow_dispatch:
   inputs:
      profile_name:
        required: true
        description: Name of profile in trestle workspace to be imported into the component definition
      component_definition_name:
        description: Name of component definition to create
        required: true
      component_title:
        required: true
        description: Name of the component in the generated component definition
      component_type:
        description: Type of component (e.g., service, policy, physical, validation, etc. )
        required: false
      component_description:
        required: true
        description: Description of the component in the generated component definition
      filter_by_profile:
        required: false
        description: Filter the component definition control by a separate profile

jobs:
  create-component:
    name: Create component definition
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone Repository
      - uses: actions/checkout@v4
      - name: Create new Component Definition and open PR
        id: trestlebot
        uses: RedHatProductSecurity/trestle-bot/actions/create-cd@main
        with:
          markdown_dir: "markdown/component-definitions"
          profile_name: ${{ github.event.inputs.profile_name }}
          component_definition_name: ${{ github.event.inputs.component_definition_name }}
          component_title: ${{ github.event.inputs.component_title }}
          component_description: ${{ github.event.inputs.component_description }}
          branch: "compdef-create-${{ github.run_id }}"
          target_branch: "main"
          commit_message: "adds ${{ github.event.inputs.component_title }} component to ${{ github.event.inputs.component_definition_name }} component definition [skip ci]"
          file_patterns: "*.json, markdown/*, rules/*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          component_type: ${{ github.event.inputs.component_type }}
          #pull_request_title: "Adds ${{ github.event.inputs.component_title }} component to ${{ github.event.inputs.component_definition_name }} component definition."
          filter_by_profile: ${{ github.event.inputs.filter_by_profile }}
          dry_run: 'true'
          config: " "
